# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_product.png', upload_to='images'),
        ),
    ]
