# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ladies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/img/no_product.png', upload_to='images'),
        ),
    ]
